.

diff --git a/tests/cut/cut-tests b/tests/cut/cut-tests
--- a/tests/cut/cut-tests
+++ b/tests/cut/cut-tests
@@ -2211,8 +2211,59 @@ else
   esac
 fi
 test -s multichar-od.E || rm -f multichar-od.E
+$xx '-d­' -f2,3 --out=_ $srcdir/8bit-delim.I > 8bit-delim.O 2> 8bit-delim.E
+code=$?
+if test $code != 0 ; then
+  $echo "Test 8bit-delim(F) failed: ../../src/cut return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp 8bit-delim.O $srcdir/8bit-delim.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE" ; then $echo "passed 8bit-delim(F)"; fi ;;
+    1) $echo "Test 8bit-delim(F) failed: files 8bit-delim.O and $srcdir/8bit-delim.X differ" 1>&2;
+       errors=`expr $errors + 1` ;;
+    2) $echo "Test 8bit-delim(F) may have failed." 1>&2;
+       $echo The command "cmp 8bit-delim.O $srcdir/8bit-delim.X" failed. 1>&2 ;
+       errors=`expr $errors + 1` ;;
+  esac
+fi
+test -s 8bit-delim.E || rm -f 8bit-delim.E
+cat $srcdir/8bit-delim.I | $xx '-d­' -f2,3 --out=_ > 8bit-delim.O 2> 8bit-delim.E
+code=$?
+if test $code != 0 ; then
+  $echo "Test 8bit-delim(|) failed: ../../src/cut return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp 8bit-delim.O $srcdir/8bit-delim.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE" ; then $echo "passed 8bit-delim(|)"; fi ;;
+    1) $echo "Test 8bit-delim(|) failed: files 8bit-delim.O and $srcdir/8bit-delim.X differ" 1>&2;
+       errors=`expr $errors + 1` ;;
+    2) $echo "Test 8bit-delim(|) may have failed." 1>&2;
+       $echo The command "cmp 8bit-delim.O $srcdir/8bit-delim.X" failed. 1>&2 ;
+       errors=`expr $errors + 1` ;;
+  esac
+fi
+test -s 8bit-delim.E || rm -f 8bit-delim.E
+$xx '-d­' -f2,3 --out=_ < $srcdir/8bit-delim.I > 8bit-delim.O 2> 8bit-delim.E
+code=$?
+if test $code != 0 ; then
+  $echo "Test 8bit-delim(<) failed: ../../src/cut return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp 8bit-delim.O $srcdir/8bit-delim.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE" ; then $echo "passed 8bit-delim(<)"; fi ;;
+    1) $echo "Test 8bit-delim(<) failed: files 8bit-delim.O and $srcdir/8bit-delim.X differ" 1>&2;
+       errors=`expr $errors + 1` ;;
+    2) $echo "Test 8bit-delim(<) may have failed." 1>&2;
+       $echo The command "cmp 8bit-delim.O $srcdir/8bit-delim.X" failed. 1>&2 ;
+       errors=`expr $errors + 1` ;;
+  esac
+fi
+test -s 8bit-delim.E || rm -f 8bit-delim.E
 if test $errors = 0 ; then
-  $echo Passed all 129 tests. 1>&2
+  $echo Passed all 132 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
