*** empty log message ***

diff --git a/tests/cp/backup-is-src b/tests/cp/backup-is-src
--- a/tests/cp/backup-is-src
+++ b/tests/cp/backup-is-src
@@ -5,18 +5,24 @@ if test "$VERBOSE" = yes; then
   cp --version
 fi
 
+. $srcdir/../lang-default
+
+pwd=`pwd`
+t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
+trap 'status=$?; cd $pwd; rm -rf $t0 && exit $status' 0
+trap '(exit $?); exit' 1 2 13 15
+
 framework_failure=0
-rm -f a a~ || framework_failure=1
+mkdir -p $tmp || framework_failure=1
+cd $tmp || framework_failure=1
+
 echo a > a || framework_failure=1
 echo a-tilde > a~ || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo 'failure in testing framework'
-  exit 1
+  echo '$0: failure in testing framework' 1>&2
+  (exit 1); exit
 fi
-
-# Make sure we get English translations.
-. $srcdir/../lang-default
 
 # This cp command should exit nonzero.
 cp --b=simple a~ a > out 2>&1 && fail=1
@@ -28,7 +34,5 @@ XXX: backing up `a' would destroy source;  `a~' not copied
 EOF
 
 cmp out2 exp || fail=1
-
-rm -f out out2 exp a a~
 
 (exit $fail); exit
