Use double quotes around diagnostic.

diff --git a/tests/cp/backup-is-src b/tests/cp/backup-is-src
--- a/tests/cp/backup-is-src
+++ b/tests/cp/backup-is-src
@@ -20,7 +20,7 @@ echo a > a || framework_failure=1
 echo a-tilde > a~ || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/cp/r-vs-symlink b/tests/cp/r-vs-symlink
--- a/tests/cp/r-vs-symlink
+++ b/tests/cp/r-vs-symlink
@@ -24,7 +24,7 @@ ln -s foo slink || framework_failure=1
 ln -s no-such-file no-file || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/fmt/long-line b/tests/fmt/long-line
--- a/tests/fmt/long-line
+++ b/tests/fmt/long-line
@@ -50,7 +50,7 @@ cat <<\EOF > exp || framework_failure=1
 EOF
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit 1
 fi
 
diff --git a/tests/ls/recursive b/tests/ls/recursive
--- a/tests/ls/recursive
+++ b/tests/ls/recursive
@@ -22,7 +22,7 @@ mkdir x y a b c a/1 a/2 a/3 || framework_failure=1
 touch f a/1/I a/1/II || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/ls/rt-1 b/tests/ls/rt-1
--- a/tests/ls/rt-1
+++ b/tests/ls/rt-1
@@ -26,7 +26,7 @@ touch -d "$date" a || framework_failure=1
 touch -d "$date" b || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/mv/i-link-no b/tests/mv/i-link-no
--- a/tests/mv/i-link-no
+++ b/tests/mv/i-link-no
@@ -25,7 +25,7 @@ ln b/FUBAR b/bar || framework_failure=1
 chmod a-w b/bar || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/mv/part-fail b/tests/mv/part-fail
--- a/tests/mv/part-fail
+++ b/tests/mv/part-fail
@@ -31,7 +31,7 @@ touch k $other_partition_tmpdir/k || framework_failure=1
 chmod u-w $other_partition_tmpdir || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/rm/dangling-symlink b/tests/rm/dangling-symlink
--- a/tests/rm/dangling-symlink
+++ b/tests/rm/dangling-symlink
@@ -21,7 +21,7 @@ ln -s no-file dangle
 ln -s / symlink
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/rm/r-1 b/tests/rm/r-1
--- a/tests/rm/r-1
+++ b/tests/rm/r-1
@@ -28,7 +28,7 @@ removed `b'
 EOF
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/rm/rm1 b/tests/rm/rm1
--- a/tests/rm/rm1
+++ b/tests/rm/rm1
@@ -22,7 +22,7 @@ mkdir -p b/a/p b/c b/d || framework_failure=1
 chmod u-w b/a || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/rm/rm2 b/tests/rm/rm2
--- a/tests/rm/rm2
+++ b/tests/rm/rm2
@@ -22,7 +22,7 @@ mkdir -p a/1/2 b/3 || framework_failure=1
 chmod u-x a/1 b || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/rm/rm3 b/tests/rm/rm3
--- a/tests/rm/rm3
+++ b/tests/rm/rm3
@@ -29,7 +29,7 @@ chmod u-w fu du empty-u || framework_failure=1
 cd ..
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/rm/sunos-1 b/tests/rm/sunos-1
--- a/tests/rm/sunos-1
+++ b/tests/rm/sunos-1
@@ -19,7 +19,7 @@ mkdir -p $tmp || framework_failure=1
 cd $tmp || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
diff --git a/tests/rm/unread2 b/tests/rm/unread2
--- a/tests/rm/unread2
+++ b/tests/rm/unread2
@@ -22,7 +22,7 @@ mkdir -p a/b || framework_failure=1
 chmod u-r a
 
 if test $framework_failure = 1; then
-  echo '$0: failure in testing framework' 1>&2
+  echo "$0: failure in testing framework" 1>&2
   (exit 1); exit
 fi
 
