cp: treat selinux warnings consistently
* src/copy.c (copy_reg): Suppress SELinux ENOTSUP warnings consistently
between the destination being present or not.  Previously we did
not suppress ENOTSUP messages when the destination was present.
(copy_internal): Use the same ENOTSUP supression method as
copy_reg() even though the issue was not seen in this case.
* tests/cp/cp-a-selinux: Add a test case for the issue and
group the other test cases in the file more coherently.
* tests/cp/cp-mv-enotsup-xattr: Do the same check for xattr
warnings, even though they did not have the issue.

diff --git a/tests/cp/cp-a-selinux b/tests/cp/cp-a-selinux
--- a/tests/cp/cp-a-selinux
+++ b/tests/cp/cp-a-selinux
@@ -60,51 +60,60 @@ test $skip = 1 \
 cd mnt                                       || framework_failure
 
 echo > f                                     || framework_failure
+
 echo > g                                     || framework_failure
-
-
 # /bin/cp from coreutils-6.7-3.fc7 would fail this test by letting cp
 # succeed (giving no diagnostics), yet leaving the destination file empty.
 cp -a f g 2>err || fail=1
 test -s g       || fail=1     # The destination file must not be empty.
 test -s err     && fail=1     # There must be no stderr output.
 
-rm -f g err
-echo > g
-
 # =====================================================
-# Here, we expect cp to fail, because it cannot set the SELinux
-# security context through NFS or a mount with fixed context.
-cp --preserve=context f g 2> out && fail=1
-
-# Here, we *do* expect the destination to be empty.
-test -s g && fail=1
-
+# Here, we expect cp to succeed and not warn with "Operation not supported"
 rm -f g
 echo > g
-# Check if -a option doesn't silence --preserve=context option diagnostics
-cp -a --preserve=context f g 2> out2 && fail=1
+cp --preserve=all f g 2>err || fail=1
+test -s g || fail=1
+grep "Operation not supported" err && fail=1
 
-# Here, we *do* expect the destination to be empty.
-test -s g && fail=1
+# =====================================================
+# The same as above except destination does not exist
+rm -f g
+cp --preserve=all f g 2>err || fail=1
+test -s g || fail=1
+grep "Operation not supported" err && fail=1
 
-# An alternative to the current approach would be to run in a confined
+# An alternative to the following approach would be to run in a confined
 # domain (maybe creating/loading it) that lacks the required permissions
 # to the file type.
 # Note: this test could also be run by a regular (non-root) user in an
 # NFS mounted directory.  When doing that, I get this diagnostic:
 # cp: failed to set the security context of `g' to `system_u:object_r:nfs_t': \
 #   Operation not supported
-sed "s/ .g' to .*//" out > k
-mv k out
-sed "s/ .g' to .*//" out2 > k
-mv k out2
-
-cat <<\EOF > exp || fail=1
+cat <<\EOF > exp || framework_failure=1
 cp: failed to set the security context of
 EOF
 
+rm -f g
+echo > g
+# =====================================================
+# Here, we expect cp to fail, because it cannot set the SELinux
+# security context through NFS or a mount with fixed context.
+cp --preserve=context f g 2> out && fail=1
+# Here, we *do* expect the destination to be empty.
+test -s g && fail=1
+sed "s/ .g' to .*//" out > k
+mv k out
 compare out exp || fail=1
+
+rm -f g
+echo > g
+# Check if -a option doesn't silence --preserve=context option diagnostics
+cp -a --preserve=context f g 2> out2 && fail=1
+# Here, we *do* expect the destination to be empty.
+test -s g && fail=1
+sed "s/ .g' to .*//" out2 > k
+mv k out2
 compare out2 exp || fail=1
 
 Exit $fail
