*** empty log message ***

diff --git a/tests/cp/no-deref-slink b/tests/cp/no-deref-slink
--- a/tests/cp/no-deref-slink
+++ b/tests/cp/no-deref-slink
@@ -1,12 +1,22 @@
 #!/bin/sh
-# This test requires ln -s.
+# FIXME: This test requires ln -s.
 # cp from 3.16 fails this test
+
 rm -rf a b
 mkdir a b
-echo foo > a/foo
+msg=bar
+echo $msg > a/foo
 cd b
 ln -s ../a/foo .
 cd ..
-./cp -d a/foo b
-test "`cat a/foo`" = foo && fail=0 || fail=1
-exit $fail
+
+# It should fail with a message something like this:
+#   ./cp: `a/foo' and `b/foo' are the same file
+./cp -d a/foo b 2>/dev/null
+
+# Fail this test if the exit status is not 1
+test $? = 1 || exit 1
+
+test "`cat a/foo`" = bar || exit 1
+
+exit 0
