upgrade to use better framework

diff --git a/tests/cp/no-deref-link2 b/tests/cp/no-deref-link2
--- a/tests/cp/no-deref-link2
+++ b/tests/cp/no-deref-link2
@@ -7,7 +7,20 @@ if test "$VERBOSE" = yes; then
   cp --version
 fi
 
-rm -rf a b
+pwd=`pwd`
+t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
+trap 'status=$?; cd $pwd; rm -rf $t0 && exit $status' 0
+trap '(exit $?); exit' 1 2 13 15
+
+framework_failure=0
+mkdir -p $tmp || framework_failure=1
+cd $tmp || framework_failure=1
+
+if test $framework_failure = 1; then
+  echo '$0: failure in testing framework' 1>&2
+  (exit 1); exit
+fi
+
 mkdir b
 msg=bar
 echo $msg > a
@@ -25,7 +38,5 @@ cp -d a b 2>/dev/null
 test $? = 1 || fail=1
 
 test "`cat a`" = $msg || fail=1
-
-rm -rf a b
 
 (exit $fail); exit
