Clean up traps.  Create files in a subdir.

diff --git a/tests/cp/same-file b/tests/cp/same-file
--- a/tests/cp/same-file
+++ b/tests/cp/same-file
@@ -13,11 +13,21 @@ LANG=C; export LANG
 VERSION_CONTROL=numbered; export VERSION_CONTROL
 
 pwd=`pwd`
+tmp=same-f-$$
+trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
+trap 'exit $?' 1 2 13 15
+
+framework_failure=0
+mkdir $tmp || framework_failure=1
+cd $tmp || framework_failure=1
+
+if test $framework_failure = 1; then
+  echo 'failure in testing framework'
+  exit 1
+fi
+
 actual=actual-$$
 expected=expected-$$
-
-trap 'status=$?; cd $pwd; rm -rf dir $actual $expected && exit $status' 0
-trap 'exit $?' 1 2 13 15
 
 exec 1> $actual
 
