*** empty log message ***

diff --git a/tests/cp/special-bits b/tests/cp/special-bits
--- a/tests/cp/special-bits
+++ b/tests/cp/special-bits
@@ -25,10 +25,11 @@ chmod u-w file || framework_failure=1
   echo ""
   echo "cd $pwd && $MAKE check TESTS=special-bits"
   echo ""
-  echo "  or"
+  echo "Here's a minimalist version.  It outputs nothing when the test"
+  echo "succeeds, and \`FAIL' if it fails."
   echo ""
   echo "cd $pwd \\"
-  echo "  && env PATH=../../src:\$PATH MAKE=$MAKE ./special-bits"
+  echo "  && env PATH=../../src:\$PATH MAKE=$MAKE ./special-bits || echo FAIL"
   echo ""
   echo '********************************************'
   exit 77
