Include /bin/sh driver framework.

diff --git a/tests/ls-2/quoting b/tests/ls-2/quoting
--- a/tests/ls-2/quoting
+++ b/tests/ls-2/quoting
@@ -1,4 +1,16 @@
-#!/usr/bin/perl -w
+#!/bin/sh
+
+: ${PERL=perl}
+: ${srcdir=.}
+
+case "$PERL" in
+  *'missing perl')
+  echo 1>&2 "$0: configure didn't find a usable version of Perl, so can't run this test"
+  exit 77
+  ;;
+esac
+
+exec $PERL -w -I$srcdir/.. -MFetish -- - << \EOF
 require 5.003;
 use strict;
 
@@ -38,3 +50,4 @@ my $verbose = $ENV{VERBOSE};
 my $prog = $ENV{PROG} || die "$0: \$PROG not specified in environment\n";
 my $fail = run_tests ($program_name, $prog, \@Tests, $save_temps, $verbose);
 exit $fail;
+EOF
