* tests/rm/one-file-system: Upon setup failure (e.g., mount failure), skip the test rather than failing.  Reported by Michael Deutschmann.

diff --git a/tests/rm/one-file-system b/tests/rm/one-file-system
--- a/tests/rm/one-file-system
+++ b/tests/rm/one-file-system
@@ -51,8 +51,8 @@ rm: skipping `a/b', since it's on a different device
 EOF
 
 if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
+  echo "$0: setup failed; skipping this test" 1>&2
+  (exit 77); exit 77
 fi
 
 fail=0
