Convert tests/misc/ to use test-lib.sh, too.

diff --git a/tests/misc/close-stdout b/tests/misc/close-stdout
--- a/tests/misc/close-stdout
+++ b/tests/misc/close-stdout
@@ -2,7 +2,7 @@
 # Ensure that several programs work fine, even with stdout initially closed.
 # This is effectively a test of closeout.c's close_stdout function.
 
-# Copyright (C) 2004, 2006 Free Software Foundation, Inc.
+# Copyright (C) 2004, 2006, 2007 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,22 +22,9 @@ if test "$VERBOSE" = yes; then
   rm --version
 fi
 
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
+. $srcdir/../test-lib.sh
 
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
-fi
-
-PATH="$pwd/../..:$PATH"
-export PATH
+p="$abs_top_builddir"
 
 fail=0
 
@@ -54,21 +41,21 @@ mv d e >&- || fail=1
 rmdir e >&- || fail=1
 touch e >&- || fail=1
 sleep 0 >&- || fail=1
-"$pwd/../../src/true" >&- || fail=1
-"$pwd/../../src/printf" '' >&- || fail=1
+"$p/src/true" >&- || fail=1
+"$p/src/printf" '' >&- || fail=1
 
 # If >&- works, ensure these fail, because stdout is closed and they
 # *do* generate output.  >&- apparently does not work in HP-UX 11.23.
 # This test is ineffective unless /dev/stdout also works.
-if "$pwd/../../src/test" -w /dev/stdout >/dev/null &&
-   "$pwd/../../src/test" ! -w /dev/stdout >&-; then
-  "$pwd/../../src/printf" 'foo' >&- 2>/dev/null && fail=1
+if "$p/src/test" -w /dev/stdout >/dev/null &&
+   "$p/src/test" ! -w /dev/stdout >&-; then
+  "$p/src/printf" 'foo' >&- 2>/dev/null && fail=1
   cp --verbose a b >&- 2>/dev/null && fail=1
 fi
 
 # Likewise for /dev/full, if /dev/full works.
 if test -w /dev/full && test -c /dev/full; then
-  "$pwd/../../src/printf" 'foo' >/dev/full 2>/dev/null && fail=1
+  "$p/src/printf" 'foo' >/dev/full 2>/dev/null && fail=1
   cp --verbose a b >/dev/full 2>/dev/null && fail=1
 fi
 
diff --git a/tests/misc/fmt-long-line b/tests/misc/fmt-long-line
--- a/tests/misc/fmt-long-line
+++ b/tests/misc/fmt-long-line
@@ -1,7 +1,7 @@
 #!/bin/sh
 # make sure fmt -s works even on long lines
 
-# Copyright (C) 2002, 2006 Free Software Foundation, Inc.
+# Copyright (C) 2002, 2006, 2007 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -21,17 +21,11 @@ if test "$VERBOSE" = yes; then
   fmt --version
 fi
 
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
+. $srcdir/../test-lib.sh
 
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-(echo ' '; yes) | head -n1000 | tr '\n' ' ' > in || framework_failure=1
+(echo ' '; yes) | head -n1000 | tr '\n' ' ' > in || framework_failure
 
-cat <<\EOF > exp || framework_failure=1
+cat <<\EOF > exp || framework_failure
   y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y
   y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y
   y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y
@@ -64,16 +58,10 @@ cat <<\EOF > exp || framework_failure=1
   y y
 EOF
 
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
-fi
-
 fail=0
 
 fmt -s in > out || fail=1
 
-cmp out exp || fail=1
-test $fail = 1 && diff out exp 2> /dev/null
+compare out exp || fail=1
 
 (exit $fail); exit $fail
diff --git a/tests/misc/nohup b/tests/misc/nohup
--- a/tests/misc/nohup
+++ b/tests/misc/nohup
@@ -1,7 +1,7 @@
 #!/bin/sh
 # test nohup
 
-# Copyright (C) 2003, 2006 Free Software Foundation, Inc.
+# Copyright (C) 2003, 2006, 2007 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -21,22 +21,8 @@ if test "$VERBOSE" = yes; then
   nohup --version
 fi
 
-. $srcdir/../envvar-check
 . $srcdir/../lang-default
-
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
-
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
-fi
+. $srcdir/../test-lib.sh
 
 fail=0
 
@@ -62,8 +48,7 @@ else
 fi
 echo 'stderr' >> exp || fail=1
 
-cmp exp err || fail=1
-test $fail = 1 && diff exp err 2> /dev/null
+compare exp err || fail=1
 rm -f nohup.out err exp
 # ----------------------
 
@@ -95,8 +80,7 @@ nohup: appending output to `nohup.out'
 nohup: cannot run command `no-such-command': No such file or directory
 EOF
 # Disable these comparisons.  Too much variation in 2nd line.
-# cmp exp err || fail=1
-# test $fail = 1 && diff exp err 2> /dev/null
+# compare exp err || fail=1
 rm -f nohup.out err exp
 # ----------------------
 
@@ -116,8 +100,7 @@ nohup: appending output to `nohup.out'
 nohup: cannot run command `./k': Permission denied
 EOF
 # Disable these comparisons.  Too much variation in 2nd line.
-# cmp exp err || fail=1
-# test $fail = 1 && diff exp err 2> /dev/null
+# compare exp err || fail=1
 
 # Make sure it fails with exit status of 127 when given too few arguments.
 nohup >/dev/null 2>&1
diff --git a/tests/misc/split-l b/tests/misc/split-l
--- a/tests/misc/split-l
+++ b/tests/misc/split-l
@@ -1,7 +1,7 @@
 #!/bin/sh
 # show that `split --lines=2' works.
 
-# Copyright (C) 2002, 2006 Free Software Foundation, Inc.
+# Copyright (C) 2002, 2006, 2007 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -21,23 +21,11 @@ if test "$VERBOSE" = yes; then
   ln --version
 fi
 
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
+. $srcdir/../test-lib.sh
 
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-printf '1\n2\n3\n4\n5\n' > in || framework_failure=1
-
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
-fi
+printf '1\n2\n3\n4\n5\n' > in || framework_failure
 
 fail=0
-
 split --lines=2 in > out || fail=1
 cat <<\EOF > exp-1
 1
@@ -51,12 +39,9 @@ cat <<\EOF > exp-3
 5
 EOF
 
-cmp xaa exp-1 || fail=1
-test $fail = 1 && diff xaa exp 2> /dev/null
-cmp xab exp-2 || fail=1
-test $fail = 2 && diff xab exp 2> /dev/null
-cmp xac exp-3 || fail=1
-test $fail = 3 && diff xac exp 2> /dev/null
+compare xaa exp-1 || fail=1
+compare xab exp-2 || fail=1
+compare xac exp-3 || fail=1
 test -f xad && fail=1
 
 (exit $fail); exit $fail
diff --git a/tests/misc/wc-files0 b/tests/misc/wc-files0
--- a/tests/misc/wc-files0
+++ b/tests/misc/wc-files0
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Show that wc's new --files0-from option works.
 
-# Copyright (C) 2006 Free Software Foundation, Inc.
+# Copyright (C) 2006, 2007 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,24 +22,11 @@ if test "$VERBOSE" = yes; then
 fi
 
 . $srcdir/../lang-default
+. $srcdir/../test-lib.sh
 
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
-
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-
-echo 2 > 2b || framework_failure=1
-echo 2 words > 2w || framework_failure=1
-printf '2b\n2w\n' |tr '\n' '\0' > names || framework_failure=1
-
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
-fi
+echo 2 > 2b || framework_failure
+echo 2 words > 2w || framework_failure
+printf '2b\n2w\n' |tr '\n' '\0' > names || framework_failure
 
 fail=0
 
@@ -50,15 +37,13 @@ cat <<\EOF > exp || fail=1
  2  3 10 total
 EOF
 
-cmp out exp || fail=1
-test $fail = 1 && diff out exp 2> /dev/null
+compare out exp || fail=1
 
 if test "$fail" = ''; then
   # Repeat the above test, but read the file name list from stdin.
   rm -f out
   wc --files0-from=- < names > out || fail=1
-  cmp out exp || fail=1
-  test $fail = 1 && diff out exp 2> /dev/null
+  compare out exp || fail=1
 fi
 
 (exit $fail); exit $fail
