tests: change misc/printf-surprise so that it doesn't segfault anymore
* tests/misc/printf-surprise: Disable MALLOC_PERTURB_, so that "make
check" no longer provokes a segfault from printf(1).  Before, that
would be detected as a known problem and cause the test to be skipped.
Adjust the test so that a segfault once again results in test failure.

diff --git a/tests/misc/printf-surprise b/tests/misc/printf-surprise
--- a/tests/misc/printf-surprise
+++ b/tests/misc/printf-surprise
@@ -54,6 +54,10 @@ fail=0
 
 mkfifo fifo || framework_failure
 
+# Disable MALLOC_PERTURB_, to avoid triggering this bug
+# http://bugs.debian.org/481543#77
+export MALLOC_PERTURB_=0
+
 head -c 10 fifo > out &
 ( ulimit -v 10000; env $prog %20000000f 0 2>err-msg > fifo )
 exit=$?
@@ -78,9 +82,10 @@ case $n_out:$diagnostic:$exit in
   10:n:0) ;; # ok, succeeds w/no diagnostic: FreeBSD 6.1
   0:y:1)  ;; # ok, glibc-2.8 and newer, when printf(3) fails with ENOMEM
 
-  *:139)     # segfault; known bug at least in debian unstable's libc6 2.7-11
-     echo 1>&2 "$0: bug in snprintf causes low-mem use of printf to segfault"
-     fail=77;;
+  # With MALLOC_PERTURB_=0, this no longer happens.
+  # *:139)     # segfault; known bug at least in debian unstable's libc6 2.7-11
+  #    echo 1>&2 "$0: bug in snprintf causes low-mem use of printf to segfault"
+  #    fail=77;;
 
   # 10:y) ;; # Fail: doesn't happen: nobody succeeds with a diagnostic
   # 0:n)  ;; # Fail pre-patch: no output, no diag
