.

diff --git a/tests/sort/sort-tests b/tests/sort/sort-tests
--- a/tests/sort/sort-tests
+++ b/tests/sort/sort-tests
@@ -1216,6 +1216,23 @@ else
   esac
 fi
 test -s t16a.err || rm -f t16a.err
+$xx -c $srcdir/t17.in > t17.out 2> t17.err
+code=$?
+if test $code != 0 ; then
+  $echo Test 17 failed: ../../src/sort return code $code differs from expected value 0 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp t17.out $srcdir/t17.exp
+  case $? in
+    0) if test "$VERBOSE" ; then $echo passed 17; fi ;; # equal files
+    1) $echo Test 17 failed: files t17.out and $srcdir/t17.exp differ 1>&2;
+       errors=`expr $errors + 1` ;;
+    2) $echo Test 17 may have failed. 1>&2;
+       $echo The command "cmp t17.out $srcdir/t17.exp" failed. 1>&2 ;
+       errors=`expr $errors + 1` ;;
+  esac
+fi
+test -s t17.err || rm -f t17.err
 if test $errors = 0 ; then
   $echo Passed all tests. 1>&2
 else
