.

diff --git a/tests/sort/sort-tests b/tests/sort/sort-tests
--- a/tests/sort/sort-tests
+++ b/tests/sort/sort-tests
@@ -1837,8 +1837,25 @@ else
   esac
 fi
 test -s neg-nls.E || rm -f neg-nls.E
+$xx  $srcdir/nul-nls.I > nul-nls.O 2> nul-nls.E
+code=$?
+if test $code != 0 ; then
+  $echo "Test nul-nls failed: ../../src/sort return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp nul-nls.O $srcdir/nul-nls.X > /dev/null 2>&1
+  case $? in
+    0) if test "$VERBOSE" ; then $echo "passed nul-nls"; fi ;;
+    1) $echo "Test nul-nls failed: files nul-nls.O and $srcdir/nul-nls.X differ" 1>&2;
+       errors=`expr $errors + 1` ;;
+    2) $echo "Test nul-nls may have failed." 1>&2;
+       $echo The command "cmp nul-nls.O $srcdir/nul-nls.X" failed. 1>&2 ;
+       errors=`expr $errors + 1` ;;
+  esac
+fi
+test -s nul-nls.E || rm -f nul-nls.E
 if test $errors = 0 ; then
-  $echo Passed all 107 tests. 1>&2
+  $echo Passed all 108 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
