.

diff --git a/tests/tail/tail-tests b/tests/tail/tail-tests
--- a/tests/tail/tail-tests
+++ b/tests/tail/tail-tests
@@ -349,7 +349,7 @@ else
   esac
 fi
 test -s terr-2.err || rm -f terr-2.err
-$xx -c99999999999999999999 < $srcdir/terr-3.in > terr-3.out 2> terr-3.err
+$xx +2cz < $srcdir/terr-3.in > terr-3.out 2> terr-3.err
 code=$?
 if test $code != 1 ; then
   $echo Test err-3 failed: ../../src/tail return code $code differs from expected value 1 1>&2
@@ -366,7 +366,7 @@ else
   esac
 fi
 test -s terr-3.err || rm -f terr-3.err
-$xx -c < $srcdir/terr-4.in > terr-4.out 2> terr-4.err
+$xx -2cX < $srcdir/terr-4.in > terr-4.out 2> terr-4.err
 code=$?
 if test $code != 1 ; then
   $echo Test err-4 failed: ../../src/tail return code $code differs from expected value 1 1>&2
@@ -383,40 +383,74 @@ else
   esac
 fi
 test -s terr-4.err || rm -f terr-4.err
-$xx - < $srcdir/tstdin-1.in > tstdin-1.out 2> tstdin-1.err
+$xx -c99999999999999999999 < $srcdir/terr-5.in > terr-5.out 2> terr-5.err
 code=$?
-if test $code != 0 ; then
-  $echo Test stdin-1 failed: ../../src/tail return code $code differs from expected value 0 1>&2
+if test $code != 1 ; then
+  $echo Test err-5 failed: ../../src/tail return code $code differs from expected value 1 1>&2
   errors=`expr $errors + 1`
 else
-  cmp tstdin-1.out $srcdir/tstdin-1.exp
+  cmp terr-5.out $srcdir/terr-5.exp
   case $? in
-    0) if test "$VERBOSE" ; then $echo passed stdin-1; fi ;; # equal files
-    1) $echo Test stdin-1 failed: files tstdin-1.out and $srcdir/tstdin-1.exp differ 1>&2;
+    0) if test "$VERBOSE" ; then $echo passed err-5; fi ;; # equal files
+    1) $echo Test err-5 failed: files terr-5.out and $srcdir/terr-5.exp differ 1>&2;
        errors=`expr $errors + 1` ;;
-    2) $echo Test stdin-1 may have failed. 1>&2;
-       $echo The command "cmp tstdin-1.out $srcdir/tstdin-1.exp" failed. 1>&2 ;
+    2) $echo Test err-5 may have failed. 1>&2;
+       $echo The command "cmp terr-5.out $srcdir/terr-5.exp" failed. 1>&2 ;
        errors=`expr $errors + 1` ;;
   esac
 fi
-test -s tstdin-1.err || rm -f tstdin-1.err
-$xx - < $srcdir/tstdin-2.in > tstdin-2.out 2> tstdin-2.err
+test -s terr-5.err || rm -f terr-5.err
+$xx -c < $srcdir/terr-6.in > terr-6.out 2> terr-6.err
 code=$?
-if test $code != 0 ; then
-  $echo Test stdin-2 failed: ../../src/tail return code $code differs from expected value 0 1>&2
+if test $code != 1 ; then
+  $echo Test err-6 failed: ../../src/tail return code $code differs from expected value 1 1>&2
   errors=`expr $errors + 1`
 else
-  cmp tstdin-2.out $srcdir/tstdin-2.exp
+  cmp terr-6.out $srcdir/terr-6.exp
   case $? in
-    0) if test "$VERBOSE" ; then $echo passed stdin-2; fi ;; # equal files
-    1) $echo Test stdin-2 failed: files tstdin-2.out and $srcdir/tstdin-2.exp differ 1>&2;
+    0) if test "$VERBOSE" ; then $echo passed err-6; fi ;; # equal files
+    1) $echo Test err-6 failed: files terr-6.out and $srcdir/terr-6.exp differ 1>&2;
        errors=`expr $errors + 1` ;;
-    2) $echo Test stdin-2 may have failed. 1>&2;
-       $echo The command "cmp tstdin-2.out $srcdir/tstdin-2.exp" failed. 1>&2 ;
+    2) $echo Test err-6 may have failed. 1>&2;
+       $echo The command "cmp terr-6.out $srcdir/terr-6.exp" failed. 1>&2 ;
        errors=`expr $errors + 1` ;;
   esac
 fi
-test -s tstdin-2.err || rm -f tstdin-2.err
+test -s terr-6.err || rm -f terr-6.err
+$xx - < $srcdir/tminus-1.in > tminus-1.out 2> tminus-1.err
+code=$?
+if test $code != 0 ; then
+  $echo Test minus-1 failed: ../../src/tail return code $code differs from expected value 0 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp tminus-1.out $srcdir/tminus-1.exp
+  case $? in
+    0) if test "$VERBOSE" ; then $echo passed minus-1; fi ;; # equal files
+    1) $echo Test minus-1 failed: files tminus-1.out and $srcdir/tminus-1.exp differ 1>&2;
+       errors=`expr $errors + 1` ;;
+    2) $echo Test minus-1 may have failed. 1>&2;
+       $echo The command "cmp tminus-1.out $srcdir/tminus-1.exp" failed. 1>&2 ;
+       errors=`expr $errors + 1` ;;
+  esac
+fi
+test -s tminus-1.err || rm -f tminus-1.err
+$xx - < $srcdir/tminus-2.in > tminus-2.out 2> tminus-2.err
+code=$?
+if test $code != 0 ; then
+  $echo Test minus-2 failed: ../../src/tail return code $code differs from expected value 0 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp tminus-2.out $srcdir/tminus-2.exp
+  case $? in
+    0) if test "$VERBOSE" ; then $echo passed minus-2; fi ;; # equal files
+    1) $echo Test minus-2 failed: files tminus-2.out and $srcdir/tminus-2.exp differ 1>&2;
+       errors=`expr $errors + 1` ;;
+    2) $echo Test minus-2 may have failed. 1>&2;
+       $echo The command "cmp tminus-2.out $srcdir/tminus-2.exp" failed. 1>&2 ;
+       errors=`expr $errors + 1` ;;
+  esac
+fi
+test -s tminus-2.err || rm -f tminus-2.err
 $xx -n 10 < $srcdir/tn-1.in > tn-1.out 2> tn-1.err
 code=$?
 if test $code != 0 ; then
@@ -554,7 +588,7 @@ else
 fi
 test -s tn-5b.err || rm -f tn-5b.err
 if test $errors = 0 ; then
-  $echo Passed all 32 tests. 1>&2
+  $echo Passed all 34 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
