Add tests for this:
	Prompt once again for `mv -i A B' when A and B are hard links
	to the same file.  This fixes a bug introduced by my 2003-04-04
	(coreutils-5.0.1) change.

diff --git a/tests/mv/i-4 b/tests/mv/i-4
--- a/tests/mv/i-4
+++ b/tests/mv/i-4
@@ -38,4 +38,18 @@ case "`cat b`" in
   *) fail=1 ;;
 esac
 
+# Ensure that mv -i a b works properly with `n' and `y'
+# responses, even when a and b are hard links to the same file.
+# This `n' test would fail (no prompt) for coreutils-5.0.1 through 5.3.0.
+echo n > n
+rm -f a b
+echo a > a
+ln a b
+mv -i a b < n >/dev/null 2>&1 || fail=1
+test -r a || fail=1
+test -r b || fail=1
+mv -i a b < y >/dev/null 2>&1 || fail=1
+test -r a && fail=1
+test -r b || fail=1
+
 exit $fail
