Convert tests/mv, too.
* tests/other-fs-tmpdir: Before, all callers would exit 77 upon failure to
find the required dir.  Now, exit 77 in this script so callers don't have to.
Adjust callers.

diff --git a/tests/mv/leak-fd b/tests/mv/leak-fd
--- a/tests/mv/leak-fd
+++ b/tests/mv/leak-fd
@@ -2,7 +2,7 @@
 # Exercise mv's file-descriptor-leak bug, reported against coreutils-5.2.1
 # and fixed (properly) on 2004-10-21.
 
-# Copyright (C) 2004, 2006 Free Software Foundation, Inc.
+# Copyright (C) 2004, 2006-2007 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,35 +16,21 @@
 
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
-
-
-# This test is relatively expensive, and might well evoke a
-# framework-failure on systems with a smaller command-line length
 # limit so don't run it by default.
-. $srcdir/../expensive
 
 if test "$VERBOSE" = yes; then
   set -x
   mv --version
 fi
 
-. $srcdir/../other-fs-tmpdir
-. $srcdir/../envvar-check
+# This test is relatively expensive, and might well evoke a
+# framework-failure on systems with a smaller command-line length
+. $srcdir/../expensive
+
 PRIV_CHECK_ARG=require-non-root . $srcdir/../priv-check
-
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
-
-if test -z "$other_partition_tmpdir"; then
-  (exit 77); exit 77
-fi
-t0="$t0 $other_partition_tmpdir"
-
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
+. $srcdir/../test-lib.sh
+cleanup_() { rm -rf "$other_partition_tmpdir"; }
+. "$abs_top_srcdir/tests/other-fs-tmpdir"
 
 b="0 1 2 3 4 5 6 7 8 9
 a b c d e f g h i j k l m n o p q r s t u v w x y z
@@ -56,16 +42,11 @@ for i in `echo $b`; do
     echo $i$j
   done
 done > .dirs
-mkdir `cat .dirs` || framework_failure=1
+mkdir `cat .dirs` || framework_failure
 sed 's,$,/f,' .dirs | xargs touch
 
 last_file=`tail -n1 .dirs`/f
-test -f $last_file || framework_failure=1
-
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
-fi
+test -f $last_file || framework_failure
 
 fail=0
 
@@ -73,7 +54,7 @@ mv * $other_partition_tmpdir || fail=1
 test -f $last_file/f && fail=1
 rm .dirs
 
-ls -A > ../out || fail=1
-test -s ../out && fail=1
+out=$(ls -A) || fail=1
+test -z "$out" || fail=1
 
 (exit $fail); exit $fail
diff --git a/tests/mv/mv-special-1 b/tests/mv/mv-special-1
--- a/tests/mv/mv-special-1
+++ b/tests/mv/mv-special-1
@@ -1,7 +1,7 @@
 #! /bin/sh
 # Test "mv" with special files.
 
-# Copyright (C) 1998, 1999, 2000, 2002, 2004, 2005, 2006 Free Software
+# Copyright (C) 1998, 1999, 2000, 2002, 2004-2007 Free Software
 # Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
@@ -22,41 +22,25 @@ if test "$VERBOSE" = yes; then
   mv --version
 fi
 
-pwd=`pwd`
-tmp=mv-spec.$$
-trap 'status=$?; cd "$pwd" && exec 1>&2; rm -rf $tmp $other_partition_tmpdir && exit $status' 0
-trap '(exit $?); exit' 1 2 13 15
-
-. $srcdir/../other-fs-tmpdir
-. $srcdir/../envvar-check
-# Make sure we get English translations.
 . $srcdir/../lang-default
-
-if test -z "$other_partition_tmpdir"; then
-  (exit 77); exit 77
-fi
+. $srcdir/../test-lib.sh
+cleanup_() { rm -rf "$other_partition_tmpdir"; }
+. "$abs_top_srcdir/tests/other-fs-tmpdir"
 
 null=mv-null
 dir=mv-dir
 
-framework_failure=0
-mkdir $tmp || framework_failure=1
-cd $tmp || framework_failure=1
-rm -f $null || framework_failure=1
-mknod $null p || framework_failure=1
-test -p $null || framework_failure=1
-mkdir -p $dir/a/b/c $dir/d/e/f || framework_failure=1
-touch $dir/a/b/c/file1 $dir/d/e/f/file2 || framework_failure=1
+rm -f $null || framework_failure
+mknod $null p || framework_failure
+test -p $null || framework_failure
+mkdir -p $dir/a/b/c $dir/d/e/f || framework_failure
+touch $dir/a/b/c/file1 $dir/d/e/f/file2 || framework_failure
 
-if test $framework_failure = 1; then
-  echo '********************************************'
-  echo 'NOTICE: unable to create test prerequisites'
-  echo '********************************************'
-  # exit 77 here to indicate that we couldn't run the test.
-  # At least running on SunOS 4.1.4, using a directory NFS mounted
-  # from an OpenBSD system, the above mknod fails.
-  (exit 77); exit 77
-fi
+# We used to...
+# exit 77 here to indicate that we couldn't run the test.
+# At least running on SunOS 4.1.4, using a directory NFS mounted
+# from an OpenBSD system, the above mknod fails.
+# It's not worth making an exception any more.
 
 fail=0
 mv --verbose $null $dir $other_partition_tmpdir > out || fail=1
@@ -87,7 +71,7 @@ cat <<EOF | sort > exp
 \`$dir/d/e/f/file2' -> \`XXX/$dir/d/e/f/file2'
 EOF
 
-cmp out2 exp || fail=1
+compare out2 exp || fail=1
 
 # cd $other_partition_tmpdir
 # ls -l -A -R $other_partition_tmpdir
