Exit 77 if we can't set up the framework (Volker Borchert reported that this test would fail because mknod failed when run on SunOS4.1.4 using NFS-mounted disk from an OpenBSD system).

diff --git a/tests/mv/mv-special-1 b/tests/mv/mv-special-1
--- a/tests/mv/mv-special-1
+++ b/tests/mv/mv-special-1
@@ -18,7 +18,10 @@ touch $dir/a/b/c/file1 $dir/d/e/f/file2 || framework_failure=1
 
 if test $framework_failure = 1; then
   echo 'failure in testing framework'
-  exit 1
+  # exit 77 here to indicate that we couldn't run the test.
+  # At least running on SunOS 4.1.4, using a directory NFS mounted
+  # from an OpenBSD system, the above mknod fails.
+  exit 77
 fi
 
 # Make sure we get English translations.
