use newer testing framework

diff --git a/tests/mv/part-rename b/tests/mv/part-rename
--- a/tests/mv/part-rename
+++ b/tests/mv/part-rename
@@ -8,13 +8,13 @@ if test "$VERBOSE" = yes; then
   mv --version
 fi
 
-pwd=`pwd`
-tmp=part-ren.$$
-trap 'status=$?; cd $pwd; exec 1>&2; rm -rf $tmp && exit $status' 0
-trap '(exit $?); exit' 1 2 13 15
-
 . $srcdir/setup
 . $srcdir/../envvar-check
+
+pwd=`pwd`
+t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
+trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
+trap '(exit $?); exit' 1 2 13 15
 
 if test -z "$other_partition_tmpdir"; then
   (exit 77); exit
@@ -22,13 +22,13 @@ fi
 t0="$t0 $other_partition_tmpdir"
 
 framework_failure=0
-mkdir $tmp || framework_failure=1
+mkdir -p $tmp || framework_failure=1
 cd $tmp || framework_failure=1
 mkdir foo || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo 'failure in testing framework'
-  exit 1
+  echo '$0: failure in testing framework' 1>&2
+  (exit 1); exit
 fi
 
 fail=0
