Update to use newer framework.

diff --git a/tests/touch/not-owner b/tests/touch/not-owner
--- a/tests/touch/not-owner
+++ b/tests/touch/not-owner
@@ -12,17 +12,17 @@ fi
 PRIV_CHECK_ARG=require-non-root . $srcdir/../priv-check
 
 pwd=`pwd`
-tmp=fail-diag.$$
-trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
-trap '(exit $?); exit' 1 2 13 15
+t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
+trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
+trap '(exit $?); exit $?' 1 2 13 15
 
 framework_failure=0
-mkdir $tmp || framework_failure=1
+mkdir -p $tmp || framework_failure=1
 cd $tmp || framework_failure=1
 
 if test $framework_failure = 1; then
-  echo 'failure in testing framework' 1>&2
-  (exit 1); exit
+  echo "$0: failure in testing framework" 1>&2
+  (exit 1); exit 1
 fi
 
 fail=0
