regenerate

diff --git a/tests/join/join-tests b/tests/join/join-tests
--- a/tests/join/join-tests
+++ b/tests/join/join-tests
@@ -21,7 +21,7 @@ export LANG
 $xx -a1 $srcdir/1a.I1 $srcdir/1a.I2 > 1a.O 2> 1a.E
 code=$?
 if test $code != 0; then
-  $echo "Test 1a failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 1a failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 1a.O $srcdir/1a.X > /dev/null 2>&1
@@ -39,7 +39,7 @@ test -s 1a.E || rm -f 1a.E
 $xx -a2 $srcdir/1b.I1 $srcdir/1b.I2 > 1b.O 2> 1b.E
 code=$?
 if test $code != 0; then
-  $echo "Test 1b failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 1b failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 1b.O $srcdir/1b.X > /dev/null 2>&1
@@ -57,7 +57,7 @@ test -s 1b.E || rm -f 1b.E
 $xx -a1 -a2 $srcdir/1c.I1 $srcdir/1c.I2 > 1c.O 2> 1c.E
 code=$?
 if test $code != 0; then
-  $echo "Test 1c failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 1c failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 1c.O $srcdir/1c.X > /dev/null 2>&1
@@ -75,7 +75,7 @@ test -s 1c.E || rm -f 1c.E
 $xx -a1 $srcdir/1d.I1 $srcdir/1d.I2 > 1d.O 2> 1d.E
 code=$?
 if test $code != 0; then
-  $echo "Test 1d failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 1d failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 1d.O $srcdir/1d.X > /dev/null 2>&1
@@ -93,7 +93,7 @@ test -s 1d.E || rm -f 1d.E
 $xx -a2 $srcdir/1e.I1 $srcdir/1e.I2 > 1e.O 2> 1e.E
 code=$?
 if test $code != 0; then
-  $echo "Test 1e failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 1e failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 1e.O $srcdir/1e.X > /dev/null 2>&1
@@ -111,7 +111,7 @@ test -s 1e.E || rm -f 1e.E
 $xx -a2 $srcdir/1f.I1 $srcdir/1f.I2 > 1f.O 2> 1f.E
 code=$?
 if test $code != 0; then
-  $echo "Test 1f failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 1f failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 1f.O $srcdir/1f.X > /dev/null 2>&1
@@ -129,7 +129,7 @@ test -s 1f.E || rm -f 1f.E
 $xx -a1 -e . $srcdir/2a.I1 $srcdir/2a.I2 > 2a.O 2> 2a.E
 code=$?
 if test $code != 0; then
-  $echo "Test 2a failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 2a failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 2a.O $srcdir/2a.X > /dev/null 2>&1
@@ -147,7 +147,7 @@ test -s 2a.E || rm -f 2a.E
 $xx -a1 -e . -o 2.1,2.2,2.3 $srcdir/2b.I1 $srcdir/2b.I2 > 2b.O 2> 2b.E
 code=$?
 if test $code != 0; then
-  $echo "Test 2b failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 2b failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 2b.O $srcdir/2b.X > /dev/null 2>&1
@@ -165,7 +165,7 @@ test -s 2b.E || rm -f 2b.E
 $xx -a1 -e . -o 2.1,2.2,2.3 $srcdir/2c.I1 $srcdir/2c.I2 > 2c.O 2> 2c.E
 code=$?
 if test $code != 0; then
-  $echo "Test 2c failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 2c failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 2c.O $srcdir/2c.X > /dev/null 2>&1
@@ -183,7 +183,7 @@ test -s 2c.E || rm -f 2c.E
 $xx -t: $srcdir/3a.I1 $srcdir/3a.I2 > 3a.O 2> 3a.E
 code=$?
 if test $code != 0; then
-  $echo "Test 3a failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 3a failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 3a.O $srcdir/3a.X > /dev/null 2>&1
@@ -201,7 +201,7 @@ test -s 3a.E || rm -f 3a.E
 $xx -v 1 $srcdir/4a.I1 $srcdir/4a.I2 > 4a.O 2> 4a.E
 code=$?
 if test $code != 0; then
-  $echo "Test 4a failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 4a failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 4a.O $srcdir/4a.X > /dev/null 2>&1
@@ -219,7 +219,7 @@ test -s 4a.E || rm -f 4a.E
 $xx -v 2 $srcdir/4b.I1 $srcdir/4b.I2 > 4b.O 2> 4b.E
 code=$?
 if test $code != 0; then
-  $echo "Test 4b failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 4b failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 4b.O $srcdir/4b.X > /dev/null 2>&1
@@ -237,7 +237,7 @@ test -s 4b.E || rm -f 4b.E
 $xx -v 1 $srcdir/4c.I1 $srcdir/4c.I2 > 4c.O 2> 4c.E
 code=$?
 if test $code != 0; then
-  $echo "Test 4c failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 4c failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 4c.O $srcdir/4c.X > /dev/null 2>&1
@@ -255,7 +255,7 @@ test -s 4c.E || rm -f 4c.E
 $xx -v 2 $srcdir/4d.I1 $srcdir/4d.I2 > 4d.O 2> 4d.E
 code=$?
 if test $code != 0; then
-  $echo "Test 4d failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 4d failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 4d.O $srcdir/4d.X > /dev/null 2>&1
@@ -273,7 +273,7 @@ test -s 4d.E || rm -f 4d.E
 $xx -v 2 $srcdir/4e.I1 $srcdir/4e.I2 > 4e.O 2> 4e.E
 code=$?
 if test $code != 0; then
-  $echo "Test 4e failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 4e failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 4e.O $srcdir/4e.X > /dev/null 2>&1
@@ -291,7 +291,7 @@ test -s 4e.E || rm -f 4e.E
 $xx -a1 -e - -o 1.1 2.2 $srcdir/5a.I1 $srcdir/5a.I2 > 5a.O 2> 5a.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5a failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5a failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5a.O $srcdir/5a.X > /dev/null 2>&1
@@ -309,7 +309,7 @@ test -s 5a.E || rm -f 5a.E
 $xx -a1 -e - -o 1.1 2.2 $srcdir/5b.I1 $srcdir/5b.I2 > 5b.O 2> 5b.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5b failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5b failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5b.O $srcdir/5b.X > /dev/null 2>&1
@@ -327,7 +327,7 @@ test -s 5b.E || rm -f 5b.E
 $xx -a1 -e - -o 1.1 2.2 $srcdir/5c.I1 $srcdir/5c.I2 > 5c.O 2> 5c.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5c failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5c failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5c.O $srcdir/5c.X > /dev/null 2>&1
@@ -345,7 +345,7 @@ test -s 5c.E || rm -f 5c.E
 $xx -a1 -e - -o 1.1 2.2 $srcdir/5d.I1 $srcdir/5d.I2 > 5d.O 2> 5d.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5d failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5d failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5d.O $srcdir/5d.X > /dev/null 2>&1
@@ -363,7 +363,7 @@ test -s 5d.E || rm -f 5d.E
 $xx -a2 -e - -o 1.1 2.2 $srcdir/5e.I1 $srcdir/5e.I2 > 5e.O 2> 5e.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5e failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5e failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5e.O $srcdir/5e.X > /dev/null 2>&1
@@ -381,7 +381,7 @@ test -s 5e.E || rm -f 5e.E
 $xx -a2 -e - -o 2.2 1.1 $srcdir/5f.I1 $srcdir/5f.I2 > 5f.O 2> 5f.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5f failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5f failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5f.O $srcdir/5f.X > /dev/null 2>&1
@@ -399,7 +399,7 @@ test -s 5f.E || rm -f 5f.E
 $xx -a1 -e - -o 2.2 1.1 $srcdir/5g.I1 $srcdir/5g.I2 > 5g.O 2> 5g.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5g failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5g failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5g.O $srcdir/5g.X > /dev/null 2>&1
@@ -417,7 +417,7 @@ test -s 5g.E || rm -f 5g.E
 $xx -a1 -e - -o 2.2 1.1 $srcdir/5h.I1 $srcdir/5h.I2 > 5h.O 2> 5h.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5h failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5h failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5h.O $srcdir/5h.X > /dev/null 2>&1
@@ -435,7 +435,7 @@ test -s 5h.E || rm -f 5h.E
 $xx -a1 -e - -o 1.1 2.2 $srcdir/5i.I1 $srcdir/5i.I2 > 5i.O 2> 5i.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5i failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5i failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5i.O $srcdir/5i.X > /dev/null 2>&1
@@ -453,7 +453,7 @@ test -s 5i.E || rm -f 5i.E
 $xx -a2 -e - -o 2.2 1.1 $srcdir/5j.I1 $srcdir/5j.I2 > 5j.O 2> 5j.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5j failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5j failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5j.O $srcdir/5j.X > /dev/null 2>&1
@@ -471,7 +471,7 @@ test -s 5j.E || rm -f 5j.E
 $xx -a2 -e - -o 2.2 1.1 $srcdir/5k.I1 $srcdir/5k.I2 > 5k.O 2> 5k.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5k failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5k failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5k.O $srcdir/5k.X > /dev/null 2>&1
@@ -489,7 +489,7 @@ test -s 5k.E || rm -f 5k.E
 $xx -a1 -e - -o 2.2 1.1 $srcdir/5l.I1 $srcdir/5l.I2 > 5l.O 2> 5l.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5l failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5l failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5l.O $srcdir/5l.X > /dev/null 2>&1
@@ -507,7 +507,7 @@ test -s 5l.E || rm -f 5l.E
 $xx -a2 -e - -o 2.2 1.1 $srcdir/5m.I1 $srcdir/5m.I2 > 5m.O 2> 5m.E
 code=$?
 if test $code != 0; then
-  $echo "Test 5m failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 5m failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 5m.O $srcdir/5m.X > /dev/null 2>&1
@@ -525,7 +525,7 @@ test -s 5m.E || rm -f 5m.E
 $xx -e - $srcdir/6a.I1 $srcdir/6a.I2 > 6a.O 2> 6a.E
 code=$?
 if test $code != 0; then
-  $echo "Test 6a failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 6a failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 6a.O $srcdir/6a.X > /dev/null 2>&1
@@ -543,7 +543,7 @@ test -s 6a.E || rm -f 6a.E
 $xx -a1 -e - $srcdir/6b.I1 $srcdir/6b.I2 > 6b.O 2> 6b.E
 code=$?
 if test $code != 0; then
-  $echo "Test 6b failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 6b failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 6b.O $srcdir/6b.X > /dev/null 2>&1
@@ -561,7 +561,7 @@ test -s 6b.E || rm -f 6b.E
 $xx -a1 -e - $srcdir/6c.I1 $srcdir/6c.I2 > 6c.O 2> 6c.E
 code=$?
 if test $code != 0; then
-  $echo "Test 6c failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 6c failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 6c.O $srcdir/6c.X > /dev/null 2>&1
@@ -579,7 +579,7 @@ test -s 6c.E || rm -f 6c.E
 $xx -a1 -e . -o 2.7 $srcdir/7a.I1 $srcdir/7a.I2 > 7a.O 2> 7a.E
 code=$?
 if test $code != 0; then
-  $echo "Test 7a failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 7a failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 7a.O $srcdir/7a.X > /dev/null 2>&1
@@ -597,7 +597,7 @@ test -s 7a.E || rm -f 7a.E
 $xx -a1 -e . -o 0,1.2 $srcdir/8a.I1 $srcdir/8a.I2 > 8a.O 2> 8a.E
 code=$?
 if test $code != 0; then
-  $echo "Test 8a failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 8a failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 8a.O $srcdir/8a.X > /dev/null 2>&1
@@ -615,7 +615,7 @@ test -s 8a.E || rm -f 8a.E
 $xx -a1 -a2 -e . -o 0,1.2 $srcdir/8b.I1 $srcdir/8b.I2 > 8b.O 2> 8b.E
 code=$?
 if test $code != 0; then
-  $echo "Test 8b failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 8b failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 8b.O $srcdir/8b.X > /dev/null 2>&1
@@ -633,7 +633,7 @@ test -s 8b.E || rm -f 8b.E
 $xx  $srcdir/9a.I1 $srcdir/9a.I2 > 9a.O 2> 9a.E
 code=$?
 if test $code != 0; then
-  $echo "Test 9a failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 9a failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 9a.O $srcdir/9a.X > /dev/null 2>&1
@@ -651,7 +651,7 @@ test -s 9a.E || rm -f 9a.E
 $xx -t: -1 1 -2 1 $srcdir/trailing-sp.I1 $srcdir/trailing-sp.I2 > trailing-sp.O 2> trailing-sp.E
 code=$?
 if test $code != 0; then
-  $echo "Test trailing-sp failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test trailing-sp failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp trailing-sp.O $srcdir/trailing-sp.X > /dev/null 2>&1
@@ -669,7 +669,7 @@ test -s trailing-sp.E || rm -f trailing-sp.E
 $xx  $srcdir/sp-vs-blank.I1 $srcdir/sp-vs-blank.I2 > sp-vs-blank.O 2> sp-vs-blank.E
 code=$?
 if test $code != 0; then
-  $echo "Test sp-vs-blank failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test sp-vs-blank failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp sp-vs-blank.O $srcdir/sp-vs-blank.X > /dev/null 2>&1
@@ -687,7 +687,7 @@ test -s sp-vs-blank.E || rm -f sp-vs-blank.E
 $xx -t§ $srcdir/8-bit-t.I1 $srcdir/8-bit-t.I2 > 8-bit-t.O 2> 8-bit-t.E
 code=$?
 if test $code != 0; then
-  $echo "Test 8-bit-t failed: ../../src/join return code $code differs from expected value 0" 1>&2
+  $echo "Test 8-bit-t failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp 8-bit-t.O $srcdir/8-bit-t.X > /dev/null 2>&1
diff --git a/tests/wc/wc-tests b/tests/wc/wc-tests
--- a/tests/wc/wc-tests
+++ b/tests/wc/wc-tests
@@ -21,7 +21,7 @@ export LANG
 cat $srcdir/a0.I | $xx -c > a0.O 2> a0.E
 code=$?
 if test $code != 0; then
-  $echo "Test a0(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a0(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a0.O $srcdir/a0.X > /dev/null 2>&1
@@ -39,7 +39,7 @@ test -s a0.E || rm -f a0.E
 $xx -c < $srcdir/a0.I > a0.O 2> a0.E
 code=$?
 if test $code != 0; then
-  $echo "Test a0(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a0(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a0.O $srcdir/a0.X > /dev/null 2>&1
@@ -57,7 +57,7 @@ test -s a0.E || rm -f a0.E
 cat $srcdir/a1.I | $xx -l > a1.O 2> a1.E
 code=$?
 if test $code != 0; then
-  $echo "Test a1(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a1(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a1.O $srcdir/a1.X > /dev/null 2>&1
@@ -75,7 +75,7 @@ test -s a1.E || rm -f a1.E
 $xx -l < $srcdir/a1.I > a1.O 2> a1.E
 code=$?
 if test $code != 0; then
-  $echo "Test a1(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a1(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a1.O $srcdir/a1.X > /dev/null 2>&1
@@ -93,7 +93,7 @@ test -s a1.E || rm -f a1.E
 cat $srcdir/a2.I | $xx -w > a2.O 2> a2.E
 code=$?
 if test $code != 0; then
-  $echo "Test a2(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a2(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a2.O $srcdir/a2.X > /dev/null 2>&1
@@ -111,7 +111,7 @@ test -s a2.E || rm -f a2.E
 $xx -w < $srcdir/a2.I > a2.O 2> a2.E
 code=$?
 if test $code != 0; then
-  $echo "Test a2(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a2(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a2.O $srcdir/a2.X > /dev/null 2>&1
@@ -129,7 +129,7 @@ test -s a2.E || rm -f a2.E
 cat $srcdir/a3.I | $xx -c > a3.O 2> a3.E
 code=$?
 if test $code != 0; then
-  $echo "Test a3(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a3(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a3.O $srcdir/a3.X > /dev/null 2>&1
@@ -147,7 +147,7 @@ test -s a3.E || rm -f a3.E
 $xx -c < $srcdir/a3.I > a3.O 2> a3.E
 code=$?
 if test $code != 0; then
-  $echo "Test a3(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a3(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a3.O $srcdir/a3.X > /dev/null 2>&1
@@ -165,7 +165,7 @@ test -s a3.E || rm -f a3.E
 cat $srcdir/a4.I | $xx -w > a4.O 2> a4.E
 code=$?
 if test $code != 0; then
-  $echo "Test a4(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a4(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a4.O $srcdir/a4.X > /dev/null 2>&1
@@ -183,7 +183,7 @@ test -s a4.E || rm -f a4.E
 $xx -w < $srcdir/a4.I > a4.O 2> a4.E
 code=$?
 if test $code != 0; then
-  $echo "Test a4(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a4(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a4.O $srcdir/a4.X > /dev/null 2>&1
@@ -201,7 +201,7 @@ test -s a4.E || rm -f a4.E
 cat $srcdir/a5.I | $xx -w > a5.O 2> a5.E
 code=$?
 if test $code != 0; then
-  $echo "Test a5(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a5(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a5.O $srcdir/a5.X > /dev/null 2>&1
@@ -219,7 +219,7 @@ test -s a5.E || rm -f a5.E
 $xx -w < $srcdir/a5.I > a5.O 2> a5.E
 code=$?
 if test $code != 0; then
-  $echo "Test a5(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a5(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a5.O $srcdir/a5.X > /dev/null 2>&1
@@ -237,7 +237,7 @@ test -s a5.E || rm -f a5.E
 cat $srcdir/a6.I | $xx -w > a6.O 2> a6.E
 code=$?
 if test $code != 0; then
-  $echo "Test a6(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a6(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a6.O $srcdir/a6.X > /dev/null 2>&1
@@ -255,7 +255,7 @@ test -s a6.E || rm -f a6.E
 $xx -w < $srcdir/a6.I > a6.O 2> a6.E
 code=$?
 if test $code != 0; then
-  $echo "Test a6(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a6(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a6.O $srcdir/a6.X > /dev/null 2>&1
@@ -273,7 +273,7 @@ test -s a6.E || rm -f a6.E
 cat $srcdir/a7.I | $xx -l > a7.O 2> a7.E
 code=$?
 if test $code != 0; then
-  $echo "Test a7(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a7(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a7.O $srcdir/a7.X > /dev/null 2>&1
@@ -291,7 +291,7 @@ test -s a7.E || rm -f a7.E
 $xx -l < $srcdir/a7.I > a7.O 2> a7.E
 code=$?
 if test $code != 0; then
-  $echo "Test a7(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a7(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a7.O $srcdir/a7.X > /dev/null 2>&1
@@ -309,7 +309,7 @@ test -s a7.E || rm -f a7.E
 cat $srcdir/a8.I | $xx -l > a8.O 2> a8.E
 code=$?
 if test $code != 0; then
-  $echo "Test a8(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a8(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a8.O $srcdir/a8.X > /dev/null 2>&1
@@ -327,7 +327,7 @@ test -s a8.E || rm -f a8.E
 $xx -l < $srcdir/a8.I > a8.O 2> a8.E
 code=$?
 if test $code != 0; then
-  $echo "Test a8(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a8(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a8.O $srcdir/a8.X > /dev/null 2>&1
@@ -345,7 +345,7 @@ test -s a8.E || rm -f a8.E
 cat $srcdir/a9.I | $xx -l > a9.O 2> a9.E
 code=$?
 if test $code != 0; then
-  $echo "Test a9(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a9(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a9.O $srcdir/a9.X > /dev/null 2>&1
@@ -363,7 +363,7 @@ test -s a9.E || rm -f a9.E
 $xx -l < $srcdir/a9.I > a9.O 2> a9.E
 code=$?
 if test $code != 0; then
-  $echo "Test a9(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test a9(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp a9.O $srcdir/a9.X > /dev/null 2>&1
@@ -381,7 +381,7 @@ test -s a9.E || rm -f a9.E
 $xx  < $srcdir/b0.I > b0.O 2> b0.E
 code=$?
 if test $code != 0; then
-  $echo "Test b0 failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test b0 failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp b0.O $srcdir/b0.X > /dev/null 2>&1
@@ -399,7 +399,7 @@ test -s b0.E || rm -f b0.E
 $xx  < $srcdir/b1.I > b1.O 2> b1.E
 code=$?
 if test $code != 0; then
-  $echo "Test b1 failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test b1 failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp b1.O $srcdir/b1.X > /dev/null 2>&1
@@ -417,7 +417,7 @@ test -s b1.E || rm -f b1.E
 cat $srcdir/c0.I | $xx -L > c0.O 2> c0.E
 code=$?
 if test $code != 0; then
-  $echo "Test c0(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test c0(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp c0.O $srcdir/c0.X > /dev/null 2>&1
@@ -435,7 +435,7 @@ test -s c0.E || rm -f c0.E
 $xx -L < $srcdir/c0.I > c0.O 2> c0.E
 code=$?
 if test $code != 0; then
-  $echo "Test c0(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test c0(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp c0.O $srcdir/c0.X > /dev/null 2>&1
@@ -453,7 +453,7 @@ test -s c0.E || rm -f c0.E
 cat $srcdir/c1.I | $xx -L > c1.O 2> c1.E
 code=$?
 if test $code != 0; then
-  $echo "Test c1(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test c1(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp c1.O $srcdir/c1.X > /dev/null 2>&1
@@ -471,7 +471,7 @@ test -s c1.E || rm -f c1.E
 $xx -L < $srcdir/c1.I > c1.O 2> c1.E
 code=$?
 if test $code != 0; then
-  $echo "Test c1(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test c1(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp c1.O $srcdir/c1.X > /dev/null 2>&1
@@ -489,7 +489,7 @@ test -s c1.E || rm -f c1.E
 cat $srcdir/c2.I | $xx -L > c2.O 2> c2.E
 code=$?
 if test $code != 0; then
-  $echo "Test c2(|) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test c2(|) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp c2.O $srcdir/c2.X > /dev/null 2>&1
@@ -507,7 +507,7 @@ test -s c2.E || rm -f c2.E
 $xx -L < $srcdir/c2.I > c2.O 2> c2.E
 code=$?
 if test $code != 0; then
-  $echo "Test c2(<) failed: ../../src/wc return code $code differs from expected value 0" 1>&2
+  $echo "Test c2(<) failed: $xx return code $code differs from expected value 0" 1>&2
   errors=`expr $errors + 1`
 else
   cmp c2.O $srcdir/c2.X > /dev/null 2>&1
