* tests/ls/stat-vs-dirent: Too many (losing) systems trigger the failure that this test checks for (stat/dirent inode mismatch at a mount point), so continue to give a diagnostic about the failure, but don't actually count it as a failure.

diff --git a/tests/ls/stat-vs-dirent b/tests/ls/stat-vs-dirent
--- a/tests/ls/stat-vs-dirent
+++ b/tests/ls/stat-vs-dirent
@@ -46,7 +46,16 @@ while :; do
       echo "$0: test failed: $t/$file: d_ino($d_ino) != st_ino($st_ino)" 1>&2
       echo "$0: This may indicate a flaw in your kernel or" \
 	     "file system implementation." 1>&2
-      fail=1
+      echo "$0: This flaw won't impact coreutils, but it may well"
+	     "affect other tools,"
+      echo "$0: so you should report it to your operating system vendor." 1>&2
+
+      # This test fails too often, and we don't want to be distracted
+      # with reports, since the code that could be affected by the losing
+      # behavior (pwd and getcwd) works around any mismatch.
+      # So do continue to issue the warning, but don't count it as a
+      # real failure.
+      # fail=1
       break
     fi
   fi
