.

diff --git a/tests/pr/pr-tests b/tests/pr/pr-tests
--- a/tests/pr/pr-tests
+++ b/tests/pr/pr-tests
@@ -3681,8 +3681,25 @@ else
   esac
 fi
 test -s 12md.E || rm -f 12md.E
+$xx --test -h x -o 0 $srcdir/margin-0.I > margin-0.O 2> margin-0.E
+code=$?
+if test $code != 0 ; then
+  $echo "Test margin-0 failed: ../../src/pr return code $code differs from expected value 0" 1>&2
+  errors=`expr $errors + 1`
+else
+  cmp margin-0.O $srcdir/margin-0.X
+  case $? in
+    0) if test "$VERBOSE" ; then $echo "passed margin-0"; fi ;;
+    1) $echo "Test margin-0 failed: files margin-0.O and $srcdir/margin-0.X differ" 1>&2;
+       errors=`expr $errors + 1` ;;
+    2) $echo "Test margin-0 may have failed." 1>&2;
+       $echo The command "cmp margin-0.O $srcdir/margin-0.X" failed. 1>&2 ;
+       errors=`expr $errors + 1` ;;
+  esac
+fi
+test -s margin-0.E || rm -f margin-0.E
 if test $errors = 0 ; then
-  $echo Passed all 216 tests. 1>&2
+  $echo Passed all 217 tests. 1>&2
 else
   $echo Failed $errors tests. 1>&2
 fi
