Adapt tests/tail-2/ to use test-lib.sh.

diff --git a/tests/tail-2/big-4gb b/tests/tail-2/big-4gb
--- a/tests/tail-2/big-4gb
+++ b/tests/tail-2/big-4gb
@@ -2,7 +2,7 @@
 # Demonstrate a bug in `tail -cN' when operating on files of size 4G and larger
 # Fixed in coreutils-4.5.2.
 
-# Copyright (C) 2002, 2003, 2006 Free Software Foundation, Inc.
+# Copyright (C) 2002, 2003, 2006-2007 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -17,28 +17,20 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-. $srcdir/../expensive
-
 if test "$VERBOSE" = yes; then
   set -x
   tail --version
 fi
 
-pwd=`pwd`
-t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
-
-framework_failure=0
-mkdir -p $tmp || framework_failure=1
-cd $tmp || framework_failure=1
+. $srcdir/../expensive
+. $srcdir/../test-lib.sh
 
 # Create a file of size exactly 4GB (2^32) with 8 bytes
 # at the beginning and another set of 8 bytes at the end.
 # The rest will be NUL bytes.  On most modern systems, the following
 # creates a file that takes up only a few KB.  Here, du -sh says 16K.
-echo abcdefgh | tr -d '\n' > big || framework_failure=1
-echo 87654321 | tr -d '\n' > tmp || framework_failure=1
+echo abcdefgh | tr -d '\n' > big || framework_failure
+echo 87654321 | tr -d '\n' > tmp || framework_failure
 # Seek 4GB - 8
 dd bs=1 seek=4294967288 if=tmp of=big 2> err || dd_failed=1
 if test "$dd_failed" = 1; then
@@ -47,11 +39,6 @@ if test "$dd_failed" = 1; then
   echo "$0: possibly because this system doesn't support large files;" 1>&2
   echo "$0: Consider rerunning this test on a different file system." 1>&2
   (exit 77); exit 77
-fi
-
-if test $framework_failure = 1; then
-  echo "$0: failure in testing framework" 1>&2
-  (exit 1); exit 1
 fi
 
 fail=0
@@ -63,7 +50,6 @@ cat <<\EOF > exp
 1
 EOF
 
-cmp out exp || fail=1
-test $fail = 1 && diff out exp 2> /dev/null
+compare out exp || fail=1
 
 (exit $fail); exit $fail
