tests: tail-2/pid: include more info upon failure
* tests/tail-2/pid: Print unexpected $state upon failing.

diff --git a/tests/tail-2/pid b/tests/tail-2/pid
--- a/tests/tail-2/pid
+++ b/tests/tail-2/pid
@@ -46,7 +46,7 @@ state=$(get_process_status_ $pid)
 if test -n "$state"; then
   case $state in
     S*) ;;
-    *) echo $0: process dead 1>&2; fail=1 ;;
+    *) echo "$0: process dead? (state=$state)" 1>&2; fail=1 ;;
   esac
   kill $pid
 fi
